android.useAndroidX=true
android.newDsl=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx3g


# Flow Neuroengine
FLOW_NEURO_BASE_URL=https://api.flowneuroengine.com
FLOW_NEURO_API_KEY=dummy_key
android.useFullClasspathForDexingTransform=true
android.suppressUnsupportedCompileSdk=37
